#use_frameworks!

platform :ios, '10.0'

target 'TrampolineBlockHook_Example' do
  pod 'TrampolineBlockHook', :path => '../'
  pod 'fishhook', :git => 'https://github.com/facebook/fishhook.git'

  target 'TrampolineBlockHook_Tests' do
    inherit! :search_paths

    
  end
end
