#use_frameworks!

platform :ios, '13.0'

target 'TrampolineBlockHook_Example' do
  pod 'TrampolineBlockHook', :path => '../'

  target 'TrampolineBlockHook_Tests' do
    inherit! :search_paths

    
  end
end
